# Generated by Django 2.1.7 on 2019-03-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='rank',
        ),
    ]
