# Generated by Django 2.1.7 on 2019-03-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='release_date',
        ),
        migrations.AddField(
            model_name='toy',
            name='base_material',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
